#!/bin/bash

#----------------------------------------------------------------------------------------------------

# defaults

models_ranges=()

make_plot_links="n"

uncs=(
	#"st"
	#"st+sy"
	"st+sy+no"
)


#----------------------------------------------------------------------------------------------------

# parse command line

while [ -n "$1" ]
do
	case "$1" in
		"-g")
				shift

				case "$1" in
					"std")
							#models_ranges+=("lt-17,ht/e012+e023:f=0.2")
							models_ranges+=("lts-100,ht/e012+e023:f=0.4")
						;;

					"bootstrap")
							models_ranges+=("bootstrap/bootstrap")
						;;

					"correlation")
							base="lts-100,ht/e012+e023"
							models_ranges+=("$base:f=0.0")
							models_ranges+=("$base:f=0.1")
							models_ranges+=("$base:f=0.2")
							models_ranges+=("$base:f=0.3")
							models_ranges+=("$base:f=0.4")
							models_ranges+=("$base:f=0.5")
							models_ranges+=("$base:f=0.6")
							models_ranges+=("$base:f=0.7")
							models_ranges+=("$base:f=0.8")
							models_ranges+=("$base:f=0.9")
							models_ranges+=("$base:f=1.0")
						;;

					*)
							echo "ERROR: unknown group $1"
							exit 1
						;;
				esac
			;;

		"-plots")
				make_plot_links="y"
			;;

		-*)
				echo "ERROR: unknown option $1"
				exit 2
			;;

		*)
				models_ranges+=("$1")
			;;
	esac

	shift
done

#----------------------------------------------------------------------------------------------------

function RunOne()
{
	local dir="$1"

	echo "* $dir"

	mkdir -p "$dir"

	# make plot links
	if [ "$make_plot_links" == "y" ]
	then
		rm -rf "$dir/plots"
		mkdir -p "$dir/plots"

		for f in plots/templates/*.asy
		do
			ln -s "../../../../../$f" "$dir/plots/"
		done
	fi

	# run fits
	cd "$dir"

	../../../../do_fits -model "$model" -range "$t_range" -unc "$unc" &> "do_fits.log"
	../../../../s_extrapolation -model "$model" -range "$t_range" &> "s_extrapolation.log"

	cd - &> /dev/null
}

#----------------------------------------------------------------------------------------------------

make -j2 || exit 1

for model_range in ${models_ranges[*]}
do
	t_range=${model_range%/*}
	model=${model_range#*/}

	for unc in ${uncs[*]}
	do
		dir="fits/$t_range/$model/$unc"

		RunOne "$dir" &
	done
done
